version: '2'
services:
    vivavoce-app:
        image: vivavoce
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vivavoce-mysql:3306/vivavoce?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vivavoce-mysql:
        extends:
            file: mysql.yml
            service: vivavoce-mysql
